name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        kubernetes:
          - '1.20.10'
          - '1.21.4'
          - '1.22.1'

    name: Testing with K8s v${{ matrix.kubernetes }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: dom, curl, intl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: pcov

      - uses: actions/cache@v3.0.1
        name: Cache Composer dependencies
        with:
          path: ~/.composer/cache/files
          key: composer-${{ hashFiles('composer.json') }}

      - uses: manusa/actions-setup-minikube@v2.4.3
        name: Setup Minikube
        with:
          minikube version: v1.17.0
          kubernetes version: "v${{ matrix.kubernetes }}"
          github token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run Kubernetes Proxy
        run: |
          kubectl proxy --port=8080 &

      - name: Load Kubernetes fixtures
        run: |
          kubectl apply -f tests/fixtures/soketi.yaml

      - name: Copy environment variables
        run: |
          cp .env.example .env

      - name: Install dependencies
        run: |
          composer install --no-interaction --no-progress --prefer-dist --optimize-autoloader

      - name: Run static analysis
        run: |
          vendor/bin/psalm

      - name: Run tests
        run: |
          vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

      - uses: codecov/codecov-action@v2.1.0
        with:
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
