name: Docker Latest

on:
  push:
    branches:
      - master
    tags-ignore:
      - "*"
  pull_request:
    tags-ignore:
      - "*"
    branches-ignore:
      - "*"

jobs:
  push:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    name: Tag Latest Release

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: dom, curl, intl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: pcov

      - uses: actions/cache@v2.1.7
        name: Cache Composer dependencies
        with:
          path: ~/.composer/cache/files
          key: composer-${{ hashFiles('composer.json') }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Install dependencies
        run: |
          composer install --no-interaction --no-progress --prefer-dist --optimize-autoloader --no-dev

      - name: Compile binary
        run: |
          php artisan app:build network-watcher --build-version=stable

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: quay.io/soketi/network-watcher:latest
          context: .
